# Ledger Lattice Hunter Configuration

# Bitcoin RPC Configuration
bitcoin_rpc:
  url: ${CHAINSTACK_BTC_RPC_URL}
  user: ${CHAINSTACK_BTC_RPC_USER}
  password: ${CHAINSTACK_BTC_RPC_PASSWORD}

# Database Configuration
database:
  mongodb:
    uri: ${MONGODB_URI}
    database_name: llh_db
    collections:
      signatures: signatures
      pubkeys: pubkeys
      vulnerabilities: vulnerabilities
      priority_targets: priority_targets

# Crawler Configuration
crawler:
  batch_size: 1000
  max_retries: 3
  timeout: 30
  concurrent_requests: 10

# Attack Configuration
attack:
  poll_interval: 60 # Time in seconds to wait before checking for new targets
  recheck_interval_hours: 24 # Time in hours to wait before re-attacking a failed target

# Lattice Attack Configuration
lattice:
  min_signatures_for_attack: 5  # Lowered for testing
  max_dimension: 100
  sieving_algorithm: "g6k"
  reduction_algorithm: "bkz"
  beta_parameter: 20
  klen: 160
  x_param: 40
  sample_selection_factor: 2  # How many times more signatures to fetch for selection
  predicate_num_signatures: 100  # Number of signatures for predicate checks

# G6K Sieving Parameters
g6k_params:
  threads: 4
  verbose: true
  seed: 0
  default_sieve: "bgj1"
  dual_mode: false
  
# Pump parameters for g6k
pump_params:
  down_sieve: true
  max_loops: 3

# Worker Configuration
workers:
  min_workers: 2
  max_workers: 10
  cpu_limit: "4"
  memory_limit: "8Gi"

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/llh.log"

# Configuration for the analysis module
analysis:
  # Enable this to have the analysis module generate a list of high-priority targets
  enable_prioritization: true
  # Criteria for a public key to be considered high-priority
  priority_criteria:
    min_age_days: 365
    min_signatures: 50